### ISSUE TITLE
Does not work for more than 1 item

### ISSUE THREAD

**Issue by mukulranjan1** [hppanpaliya/Walmart-Invoice-Exporter#2]

**Comment by hppanpaliya** [comment]
Hi @mukulranjan1,
Could you please send over a screen recording of what’s going wrong? That will help us understand the issue better and troubleshoot more effectively.

**Comment by mukulranjan1** [comment]
https://github.com/user-attachments/assets/18a68677-2d51-4b63-870c-52e8eeed93b8

attached is the video of steps I did

**Comment by hppanpaliya** [comment]
Hi @mukulranjan1,  

Thank you for sharing the video—it helped me identify the issue. The error occurs because the 2nd order is a pickup/in-store order, and I haven’t tested the extension on newer pickup or in-store purchases before.  

Here’s what I found:  
1. **Pickup/In-Store Orders:** These have 21-digit order numbers, and the extension needs an update to handle this format.  
2. **HTML Content Retrieval:** For in-store orders, the URL must include the `?storePurchase=true` parameter to fetch the correct HTML content.  

Could you please share the URL of the second order after clicking "View Details"? That will help me validate the fix and ensure everything works correctly.  

In the meantime, you can try the updated version of the extension with these fixes applied:  

1. Download the updated extension from the "instore-order-fix-21-digits" branch:  
   [Download ZIP](https://codeload.github.com/hppanpaliya/Walmart-Invoice-Exporter/zip/refs/heads/instore-order-fix-21-digits).  
2. Extract the ZIP file.  
3. Go to Chrome’s **Extensions** page, enable **Developer Mode** (top-right corner), and click **Load Unpacked**.  
4. Select the extracted folder.  

Alternatively, you can download the `.crx` file directly:  
[Download CRX](https://filebin.net/x5lealkrgdke2gkg/Walmart-invoice-2.3.crx).  
After enabling **Developer Mode** on the Chrome Extensions page, drag and drop the file to install it.  

Please let me know if this resolves the issue or if you encounter any further problems.

**Comment by mukulranjan1** [comment]
Thanks Harshal, for helping and fixing this.
The tool you built is awesome, may I suggest if possible to extend the tool
to get same from other stores like Home Depot/Amazon etc
Here is the link you asked for.

https://www.walmart.com/orders/230162011006518448293?groupId=0&storePurchase=true


Thanks & Regards
Mukul Ranjan
Mobile# 909-687-5827

**Comment by hppanpaliya** [comment]
Hi @mukulranjan1,

Thank you for sharing the link and for your kind words about the extension—it means a lot! I’m glad we could identify the issue, and I’ll release the updated extension on the Chrome Web Store shortly.

As for Home Depot and Amazon, I believe there’s already an extension available for Amazon. Regarding Home Depot, I haven’t used it, so I wouldn’t be able to develop a similar tool at this time.

Thanks again for your help in debugging this issue!

Best regards,
Harshal
